// Wuji Legion · 进化主帅与三层记忆（P4）
import { z } from 'zod';
const memoryItem=z.object({key:z.string(),content:z.string(),evidence:z.string(),updatedAt:z.number()});
export const memorySchema=z.object({core:z.array(memoryItem),working:z.array(memoryItem),episodic:z.array(memoryItem),version:z.number()});
export const memoryInit=()=>({core:[],working:[],episodic:[],version:0});
export function applyMemory(s,e){if(e.type!=='wuji/memory/write')return s;const {tier,key,content,evidence}=e.data;if(!['core','working','episodic'].includes(tier))return s;const list=s[tier].filter(x=>x.key!==key);list.push({key,content,evidence,updatedAt:e.time||Date.now()});const limits={core:32,working:16,episodic:64};return{...s,[tier]:list.slice(-limits[tier]),version:s.version+1}}
export const memoryProjection={key:'wuji.memory',schema:memorySchema,init:memoryInit,apply:applyMemory,view:s=>s,stateVersion:1};
const evolution=z.object({artifactId:z.string(),version:z.number(),parents:z.array(z.string()),complementMatrix:z.array(z.object({parent:z.string(),strength:z.string(),gap:z.string(),kept:z.boolean()})),probe:z.object({name:z.string(),passed:z.boolean(),evidence:z.string()}),status:z.enum(['candidate','promoted','rejected'])});
export const evolutionSchema=z.object({artifacts:z.array(evolution),version:z.number()});
export const evolutionInit=()=>({artifacts:[],version:0});
export function applyEvolution(s,e){if(e.type!=='wuji/evolution/change')return s;const item=e.data.artifact,i=s.artifacts.findIndex(x=>x.artifactId===item.artifactId&&x.version===item.version),a=[...s.artifacts];if(i>=0)a[i]=item;else a.push(item);return{artifacts:a,version:s.version+1}}
export const evolutionProjection={key:'wuji.evolution',schema:evolutionSchema,init:evolutionInit,apply:applyEvolution,view:s=>s,stateVersion:1};
export const memoryWriteTool={name:'wuji_memory_write',description:'有界三层记忆写回：core/working/episodic；必须附证据。',parameters:{type:'object',properties:{tier:{type:'string',enum:['core','working','episodic']},key:{type:'string'},content:{type:'string'},evidence:{type:'string'}},required:['tier','key','content','evidence']},output:{schema:{type:'object'},render(_a,v){return[{type:'text',text:JSON.stringify(v)}]}},async execute(args,exec){if(!exec.agent?.session)throw new Error('记忆写回需要 Session');exec.agent.session.append('wuji/memory/write',args);return{tier:args.tier,key:args.key,status:'written'}}};
export const evolutionProposeTool={name:'wuji_evolution_propose',description:'进化主帅：提交互补矩阵、新物种候选与行为探针结果；不是A/B竞赛。',parameters:{type:'object',properties:{artifact:{type:'object'}},required:['artifact']},output:{schema:{type:'object'},render(_a,v){return[{type:'text',text:JSON.stringify(v)}]}},async execute(args,exec){const a=args.artifact;if(!a?.artifactId||!Array.isArray(a.parents)||a.parents.length<2||!Array.isArray(a.complementMatrix)||!a.probe?.evidence)throw new Error('候选必须含两个以上父能力、互补矩阵和行为探针证据');const artifact={...a,status:a.probe.passed?'candidate':'rejected'};exec.agent.session.append('wuji/evolution/change',{artifact});return{artifactId:a.artifactId,version:a.version,status:artifact.status}}};
export const evolutionPromoteTool={name:'wuji_evolution_promote',description:'只有行为探针通过且有证据的候选才能版本化晋升；旧版本不覆盖。',parameters:{type:'object',properties:{artifact:{type:'object'}},required:['artifact']},output:{schema:{type:'object'},render(_a,v){return[{type:'text',text:JSON.stringify(v)}]}},async execute(args,exec){const a=args.artifact;if(!a?.probe?.passed||!a.probe.evidence)throw new Error('晋升必须有通过的行为探针与证据');const artifact={...a,status:'promoted'};exec.agent.session.append('wuji/evolution/change',{artifact});return{artifactId:a.artifactId,version:a.version,status:'promoted'}}};
