import { z } from 'zod';
const requirementUnit=z.object({id:z.string(),revision:z.number(),goal:z.string(),dont:z.string(),constraints:z.array(z.string()),acceptance:z.string(),status:z.enum(['draft','confirmed','replaced']),sourceMsgId:z.string()});
export const requirementSchema=z.object({frame:z.array(z.object({id:z.string(),goal:z.string(),status:z.string()})),active:requirementUnit.nullable(),version:z.number()});
export const requirementInit=()=>({units:[],activeUnitId:null,version:0});
export function applyRequirement(s,e){if(e.type==='wuji/requirement/change'){const {unitId,patch}=e.data,i=s.units.findIndex(x=>x.id===unitId),u=[...s.units];if(i>=0)u[i]={...u[i],...patch,revision:u[i].revision+1};else u.push({revision:1,...patch,id:unitId});return {...s,units:u,version:s.version+1}}if(e.type==='wuji/requirement/activate')return {...s,activeUnitId:e.data.unitId,version:s.version+1};return s}
export function viewRequirement(s){const active=s.units.find(u=>u.id===s.activeUnitId)||null;return {frame:s.units.map(u=>({id:u.id,goal:u.goal,status:u.status})),active,version:s.version}}
export const requirementProjection={key:'wuji.requirement',schema:requirementSchema,init:requirementInit,apply:applyRequirement,view:viewRequirement,stateVersion:2};
const taskNode=z.object({taskId:z.string(),deps:z.array(z.string()),assignedTo:z.string(),requirement:z.string(),input:z.string(),output:z.string(),returnFormat:z.string(),failurePolicy:z.enum(['retry','reangle','report']),status:z.enum(['pending','running','success','failed']),evidence:z.string().nullable()});
export const taskSchema=z.object({frame:z.array(z.object({taskId:z.string(),assignedTo:z.string(),status:z.string(),deps:z.array(z.string())})),active:taskNode.nullable(),version:z.number()});
export const taskInit=()=>({nodes:[],activeNodeId:null,version:0});
export function applyTask(s,e){if(e.type==='wuji/task/change'){const {taskId,patch}=e.data,i=s.nodes.findIndex(n=>n.taskId===taskId),n=[...s.nodes];if(i>=0)n[i]={...n[i],...patch};else n.push({taskId,...patch});return {...s,nodes:n,version:s.version+1}}if(e.type==='wuji/task/status')return {...s,nodes:s.nodes.map(n=>n.taskId===e.data.taskId?{...n,status:e.data.status,evidence:e.data.evidence??n.evidence}:n),version:s.version+1};if(e.type==='wuji/task/activate')return {...s,activeNodeId:e.data.taskId,version:s.version+1};return s}
export function viewTask(s){const active=s.nodes.find(n=>n.taskId===s.activeNodeId)||null;return {frame:s.nodes.map(n=>({taskId:n.taskId,assignedTo:n.assignedTo,status:n.status,deps:n.deps})),active,version:s.version}}
export const taskProjection={key:'wuji.task',schema:taskSchema,init:taskInit,apply:applyTask,view:viewTask,stateVersion:2};
const advice=z.object({adviceId:z.string(),officer:z.string(),content:z.string(),evidence:z.string(),userDecision:z.enum(['adopted','rejected','deferred','pending']),affectedRequirement:z.string().nullable()});
export const officerAdviceSchema=z.object({frame:z.array(z.object({adviceId:z.string(),officer:z.string(),userDecision:z.string()})),active:advice.nullable(),version:z.number()});
export const officerAdviceInit=()=>({advices:[],activeAdviceId:null,version:0});
export function applyOfficerAdvice(s,e){if(e.type==='wuji/officer-advice/change'){const {adviceId,patch}=e.data,i=s.advices.findIndex(a=>a.adviceId===adviceId),a=[...s.advices];if(i>=0)a[i]={...a[i],...patch};else a.push({adviceId,...patch});return {...s,advices:a,version:s.version+1}}if(e.type==='wuji/officer-advice/decision')return {...s,advices:s.advices.map(a=>a.adviceId===e.data.adviceId?{...a,userDecision:e.data.userDecision}:a),version:s.version+1};if(e.type==='wuji/officer-advice/activate')return {...s,activeAdviceId:e.data.adviceId,version:s.version+1};return s}
export function viewOfficerAdvice(s){const active=s.advices.find(a=>a.adviceId===s.activeAdviceId)||null;return {frame:s.advices.map(a=>({adviceId:a.adviceId,officer:a.officer,userDecision:a.userDecision})),active,version:s.version}}
export const officerAdviceProjection={key:'wuji.officer-advice',schema:officerAdviceSchema,init:officerAdviceInit,apply:applyOfficerAdvice,view:viewOfficerAdvice,stateVersion:2};
export default {name:'wuji-host-projection',apply(ctx){ctx.inject(['sessionProjections'],p=>{p.sessionProjections.register(requirementProjection);p.sessionProjections.register(taskProjection);p.sessionProjections.register(officerAdviceProjection)})}};
